services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - JWT_SECRET=ultra_secreta_userconectar_2025
      - JWT_EXPIRES_IN=3600s
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: always
    networks:
      - userconectar_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always
    networks:
      - userconectar_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - userconectar_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always
    networks:
      - userconectar_network

volumes:
  postgres_data:

networks:
  userconectar_network:
    driver: bridge